### ISSUE TITLE
Error on ExportDataset(website=NULL)

### ISSUE THREAD

**Issue by samgregory** [giocomai/castarter#6]
Hi,

Loving the packing - managed to follow the vingette and create myself a dataset. Found a bug on this line for the ExportDataset where it tries to get CastarterOptions("website") but assigns it to the variable project not website <- CastarterOptions("website")

https://github.com/giocomai/castarter/blob/b4d7d94cd045165551dc2fd65b39e15093ceef89/R/extractMetadata.R#L335

**Comment by giocomai** [comment]
Thanks for this! The package is mostly functional, and I still routinely use it. Beyond the vignette, you may wnat to check out the documentation of individual functions in case of doubt. However, I wrote this when I was a much less experienced R programmer, so the codebase is not structured in a way that would help prevent trivial errors such as this one. I'll be hopefully get some time to overhaul the whole package sooner or later. Fix for this coming in a second.
